summary: Check agent status

prepare: |
    test -n "$(command -v lxd.lxc)"

execute: |
    if [ -n "$AGENT_ID" ]; then
        agents="$AGENT_PREFIX-$AGENT_ID"
    else
        agents=$(lxd.lxc list --format csv | cut -d ',' -f1)
    fi

    for agent_name in $agents; do
        lxd.lxc exec "$agent_name" -- sudo journalctl --vacuum-time=7d
        lxd.lxc exec "$agent_name" -- sudo find /home/ubuntu/actions-runner/_diag -mtime +7 -name 'Runner_*.log' -exec rm {} \;

        current_externals=$(lxd.lxc exec "$agent_name" -- readlink -f /home/ubuntu/actions-runner/externals)
        lxd.lxc exec "$agent_name" -- find /home/ubuntu/actions-runner/ -maxdepth 1 -name "externals.*" -type d -not -path "$current_externals" -exec rm -r {} \;

        current_bin=$(lxd.lxc exec "$agent_name" -- readlink -f /home/ubuntu/actions-runner/bin)
        lxd.lxc exec "$agent_name" -- find /home/ubuntu/actions-runner/ -maxdepth 1 -name "bin.*" -type d -not -path "$current_bin" -exec rm -r {} \;
    done
