summary: Check agent status

prepare: |
    test -n "$(command -v lxd.lxc)"

execute: |
    if [ -n "$AGENT_ID" ]; then
        agents="$AGENT_PREFIX-$AGENT_ID"
    else
        agents=$(lxd.lxc list --format csv | cut -d ',' -f1)
    fi

    for agent_name in $agents; do
        service_unit="actions.runner.snapcore-$PROJECT_NAME.$agent_name.service"
        lxd.lxc exec "$agent_name" -- sudo systemctl show -p User "$service_unit" | MATCH "User=ubuntu"
        lxd.lxc exec "$agent_name" -- sudo systemctl status "$service_unit" | MATCH "Active: active"
    done
