summary: Update service accout for the service agents specified

prepare: |
    test -f "$DATA_PATH"/spread-runner.tar
    test -n "$SA_FILE"
    test -f "$PROJECT_PATH/$SA_FILE"

restore: |
    rm -rf spread-runner spread-runner.tar

execute: |
    # Add the new sa file to the spread-runner.tar
    cp "$DATA_PATH"/spread-runner.tar "$PWD"
    tar -xf spread-runner.tar
    cp "$TASKSLIB"/setup-sa.sh spread-runner
    cp "$PROJECT_PATH/$SA_FILE" spread-runner/sa.json
    tar cf spread-runner.tar spread-runner
    mv spread-runner.tar "$DATA_PATH"

    if [ -n "$AGENT_ID" ]; then
        agents="$AGENT_PREFIX-$AGENT_ID"
    else
        agents=$(lxd.lxc list --format csv | cut -d ',' -f1)
    fi

    for agent_name in $agents; do
        lxd.lxc file push "$DATA_PATH"/spread-runner.tar "$agent_name"/tmp/spread-runner.tar
        lxd.lxc exec "$agent_name" -- tar -C /tmp -xf /tmp/spread-runner.tar
        lxd.lxc --cwd /tmp/spread-runner exec "$agent_name" -- ./setup-sa.sh
        lxd.lxc exec "$agent_name" -- rm -rf /tmp/spread-runner
    done
