summary: Update spread for the service agents specified

prepare: |
    test -n "$(command -v go)"

restore: |
    rm -rf ~/go/bin/spread

execute: |
    # Update spread version
    go get -u github.com/snapcore/spread/cmd/spread

    if [ -n "$AGENT_ID" ]; then
        agents="$AGENT_PREFIX-$AGENT_ID"
    else
        agents=$(lxd.lxc list --format csv | cut -d ',' -f1)
    fi

    for agent in $agents; do
        lxd.lxc file push ~/go/bin/spread "$agent"/tmp/spread-runner/spread
    done
