summary: Update containers with the code needed

prepare: |
    test -n "$AGENT_PREFIX"

execute: |

    if [ -n "$AGENT_ID" ]; then
        agents="$AGENT_PREFIX-$AGENT_ID"
    else
        agents=$(lxd.lxc list --format csv | cut -d ',' -f1)
    fi

    for agent_name in $agents; do
        echo "Updating the agent"
        # ADD THE CODE HERE
    done
